### ISSUE TITLE
Repeated last author when displaying all authors

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#31]
The last author is repeated when using these settings:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/3a61d45a-e37a-44cb-8f7a-164c1b14de03)

You can simply untick the Last author to fix the problem, so it is not really a big issue. But I just put it here as a note for further considerations.

**Comment by github-young** [comment]
fixed in [v3.6.1](https://github.com/github-young/zotero-better-authors/releases/tag/v3.6.1)

**Comment by mjthoraval** [comment]
I merge the discussion on this with the other issue https://github.com/github-young/zotero-better-authors/issues/32 for clarity.

What I want to achieve is to show all authors, with the Lsat author symbol still displayed on the last author.

If I use the settings originally described here, I still get the repeated last author:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/64dd0427-495a-4c8d-8c32-89e7fe7d69cf)

If I use the settings from the other issue, I am still missing the Last author symbol:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/12f81363-d5fe-4de7-b9e6-d4a9dc73d7e1)

Which one should be correct to achieve what I want?

**Comment by mjthoraval** [comment]
Something went wrong in the update I guess...
I have uninstalled the plugin, disabled all other plugins, and reinstalled again the latest version.

Here is what I get now:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/efbf118a-35d8-469e-8720-690c85904768)
This seems to be what I am looking for.

And I get the problem in this one is related to the `et al.` feature request https://github.com/github-young/zotero-better-authors/issues/33:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/b44a64b9-3ea5-4dc5-869d-72a8b3d42ac1)

**Comment by github-young** [comment]
OK.

The update works well on my client. I am not sure about the reason.

But maybe clearing all the `extensions.zotero.betterauthors.` and `extensions.zotero.lastauthor.` lines in the `prefs.js` in the profile directory could help (make sure to do it when all Zotero instances are closed, otherwise the changes are not saved.). These settings are not removed when you remove a plugin. So some default values may remain in this configuration file.

![图片](https://github.com/github-young/zotero-better-authors/assets/19162282/1e0bc26b-2315-46fe-9e7e-b1e7fe34e7cf)
